apiVersion: apps/v1
kind: Deployment
metadata:
    name: catalogue
spec:
    replicas: 2
    selector:
        matchLabels:
            app: catalogue
    template:
        metadata:
            labels:
                app: catalogue
        spec:
            containers:
                - name: catalogue
                  image: catalogue-service
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: http
                      - containerPort: 5000
                        name: grpc
                  env:
                      - name: Auth0__Domain
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Domain
                      - name: Auth0__Audience
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Audience
                      - name: ConnectionStrings__DbConnection
                        value: "Host=postgres;Port=5432;Database=CatalogueServiceDatabase;Username=postgres;Password=admin"
                      - name: ConnectionStrings__ProfileService
                        value: "http://profile-service.default.svc.cluster.local:5011"
                      - name: RabbitMQ__Host
                        value: "rabbitmq://rabbitmq.test-rabbitmq.svc.cluster.local"
                      - name: Cors__Origins__0
                        value: "http://localhost:3000"
                      - name: Minio__Endpoint
                        value: minio-service.default.svc.cluster.local:9000
                      - name: Minio__AccessKey
                        valueFrom:
                            secretKeyRef:
                                name: minio-secrets
                                key: RootUser
                      - name: Minio__SecretKey
                        valueFrom:
                            secretKeyRef:
                                name: minio-secrets
                                key: RootPassword
                      - name: Minio__BucketName
                        value: ems-estate
---
apiVersion: v1
kind: Service
metadata:
    name: catalogue-service
spec:
    type: LoadBalancer
    selector:
        app: catalogue
    ports:
        - name: service-http
          protocol: TCP
          port: 5002
          targetPort: 8080
        - name: service-grpc
          protocol: TCP
          port: 5012
          targetPort: 5000
