apiVersion: apps/v1
kind: Deployment
metadata:
    name: chat
spec:
    replicas: 2
    selector:
        matchLabels:
            app: chat
    template:
        metadata:
            labels:
                app: chat
        spec:
            containers:
                - name: chat
                  image: chat-service
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 80
                        name: chat-port
                  env:
                      - name: Auth0__Domain
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Domain
                      - name: Auth0__Audience
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Audience
                      - name: ConnectionStrings__DbConnection
                        value: "Host=postgres;Port=5432;Database=ChatServiceDatabase;Username=postgres;Password=admin"
                      - name: ConnectionStrings__ProfileService
                        value: "https://profile-service.svc.cluster.local:80"
                      - name: ConnectionStrings__CatalogueService
                        value: "https://catalogue-service.svc.cluster.local:80"
                      - name: RabbitMQ__Host
                        value: "rabbitmq://rabbitmq.test-rabbitmq.svc.cluster.local"
                      - name: Cors__Origins__0
                        value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
    name: chat-service
spec:
    selector:
        app: chat
    ports:
        - name: chat-service-port
          protocol: TCP
          port: 80
          targetPort: chat-port
