apiVersion: apps/v1
kind: Deployment
metadata:
    name: chat
spec:
    replicas: 1
    selector:
        matchLabels:
            app: chat
    template:
        metadata:
            labels:
                app: chat
        spec:
            containers:
                - name: chat
                  image: chat-service
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: http
                  env:
                      - name: Auth0__Domain
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Domain
                      - name: Auth0__Audience
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Audience
                      - name: ConnectionStrings__DbConnection
                        value: "Host=postgres;Port=5432;Database=ChatServiceDatabase;Username=postgres;Password=admin"
                      - name: ConnectionStrings__ProfileService
                        value: "http://profile-service.default.svc.cluster.local:5011"
                      - name: ConnectionStrings__CatalogueService
                        value: "http://catalogue-service.default.svc.cluster.local:5012"
                      - name: RabbitMQ__Host
                        value: "rabbitmq://rabbitmq.test-rabbitmq.svc.cluster.local"
                      - name: Cors__Origins__0
                        value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
    name: chat-service
spec:
    type: LoadBalancer
    selector:
        app: chat
    ports:
        - name: service-http
          protocol: TCP
          port: 5003
          targetPort: 8080
