apiVersion: apps/v1
kind: Deployment
metadata:
    name: notification
spec:
    replicas: 2
    selector:
        matchLabels:
            app: notification
    template:
        metadata:
            labels:
                app: notification
        spec:
            containers:
                - name: notification
                  image: notification-service
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: http
                  env:
                      - name: Auth0__Domain
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Domain
                      - name: Auth0__Audience
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Audience
                      - name: ConnectionStrings__DbConnection
                        value: "Host=postgres;Port=5432;Database=NotificationServiceDatabase;Username=postgres;Password=admin"
                      - name: ConnectionStrings__ProfileService
                        value: "http://profile-service.default.svc.cluster.local:5011"
                      - name: RabbitMQ__Host
                        value: "rabbitmq://rabbitmq.test-rabbitmq.svc.cluster.local"
                      - name: Cors__Origins__0
                        value: "http://localhost:3000"
---
apiVersion: v1
kind: Service
metadata:
    name: notification-service
spec:
    type: LoadBalancer
    selector:
        app: notification
    ports:
        - name: service-http
          protocol: TCP
          port: 5004
          targetPort: 8080
