apiVersion: apps/v1
kind: Deployment
metadata:
    name: profile
spec:
    replicas: 2
    selector:
        matchLabels:
            app: profile
    template:
        metadata:
            labels:
                app: profile
        spec:
            containers:
                - name: profile
                  image: profile-service
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                        name: http
                      - containerPort: 5000
                        name: grpc
                  env:
                      - name: Auth0__Domain
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Domain
                      - name: Auth0__Audience
                        valueFrom:
                            secretKeyRef:
                                name: auth0-secrets
                                key: Audience
                      - name: ConnectionStrings__ProfileDatabase
                        value: "Host=postgres;Port=5432;Database=ProfileDb;Username=postgres;Password=admin"
                      - name: ConnectionStrings__CatalogueService
                        value: http://catalogue-service.default.svc.cluster.local:5012
                      - name: "ConnectionStrings__Redis"
                        value: redis-service.default.svc.cluster.local:6379
                      - name: Cors__Origins__0
                        value: "http://localhost:3000"
                      - name: Minio__Endpoint
                        value: minio-service.default.svc.cluster.local:9000
                      - name: Minio__AccessKey
                        valueFrom:
                            secretKeyRef:
                                name: minio-secrets
                                key: RootUser
                      - name: Minio__SecretKey
                        valueFrom:
                            secretKeyRef:
                                name: minio-secrets
                                key: RootPassword
                      - name: Minio__BucketName
                        value: ems-profile
---
apiVersion: v1
kind: Service
metadata:
    name: profile-service
spec:
    type: LoadBalancer
    selector:
        app: profile
    ports:
        - name: service-http
          protocol: TCP
          port: 5001
          targetPort: 8080
        - name: service-grpc
          protocol: TCP
          port: 5011
          targetPort: 5000
