name: .NET with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for CatalogueService
      run: dotnet restore ./CatalogueService

    - name: Restore dependencies for ChatService
      run: dotnet restore ./ChatService

    - name: Restore dependencies for NotificationService
      run: dotnet restore ./NotificationService

    - name: Restore dependencies for ProfileService
      run: dotnet restore ./ProfileService

    - name: Build CatalogueService
      run: dotnet build ./CatalogueService --no-restore --configuration Release

    - name: Build ChatService
      run: dotnet build ./ChatService --no-restore --configuration Release

    - name: Build NotificationService
      run: dotnet build ./NotificationService --no-restore --configuration Release

    - name: Build ProfileService
      run: dotnet build ./ProfileService --no-restore --configuration Release

    - name: Test CatalogueService
      run: dotnet test ./CatalogueService --no-build --verbosity normal --configuration Release

    - name: Test ChatService
      run: dotnet test ./ChatService --no-build --verbosity normal --configuration Release

    - name: Test NotificationService
      run: dotnet test ./NotificationService --no-build --verbosity normal --configuration Release

    - name: Test ProfileService
      run: dotnet test ./ProfileService --no-build --verbosity normal --configuration Release

  analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sonar Scan
      uses: highbyte/sonarscan-dotnet@v2.3.0
      with:
        sonarProjectKey: ${{ vars.SONARPROJECTKEY }}
        sonarProjectName: ${{ vars.SONARPROJECTNAME }}
        sonarOrganization: ${{ vars.SONARORGANIZATION }}
        dotnetBuildArguments: ./CatalogueService --configuration Release
        dotnetTestArguments: ./CatalogueService --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.coverage.exclusions="${{env.EXCLUDE_FROM_COVERAGE}}" /d:sonar.exclusions="${{env.EXCLUDE_FROM_SONAR}}" 
    env:
        EXCLUDE_FROM_COVERAGE: "**/Program.cs"
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        EXCLUDE_FROM_SONAR: "**/Migrations/*, **/Dockerfile"
